### ISSUE TITLE
AAAAA

### ISSUE THREAD

**Issue by lucacome** [lucacome/workflows#36]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-configuration-snippet
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: 
```

wrong!2aa33
