### ISSUE TITLE
why

### ISSUE THREAD

**Issue by lucacome** [lucacome/workflows#38]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-configuration-snippet
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: 
```

wrong!2aa33

**Comment by lucacome** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-configuration-snippet
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: 
```

wrong!2aa33


dddd
